Check we could actually build something.

diff --git a/nacl/nacl-gcc-prep b/nacl/nacl-gcc-prep
--- a/nacl/nacl-gcc-prep
+++ b/nacl/nacl-gcc-prep
@@ -67,6 +67,7 @@ printf("The compilation worked.\n");
 }
 EOF
 
+worked=0
 for ar in $arlist; do
    arch=`basename \`dirname $ar\``
    incpath=`dirname $ar`/../../include/$arch
@@ -76,10 +77,16 @@ for ar in $arlist; do
      naclbuilddir=`echo $ar | sed -e s,/libnacl.a,,`
      echo "${incpath}" >naclinc.txt
      echo "${ar}" >nacllib.txt
+     worked=1
      break
    fi
 done
 rm -f test test.c
+
+if [ $worked -eq 0 ]; then
+    echo "Library present but couldn't build the test program"
+    exit 1
+fi
 
 # Create nacl.h for lazy programmers
 (cd ${incpath} ; find . -name \*.h -a \! -name mphlr.h -a \! -name nacl.h | sed -e 's,\./\(.*\),#include <\1>,') >${incpath}/nacl.h
