Remove old payload when updating a manifest with a new payload

diff --git a/tests/dna_rhizome b/tests/dna_rhizome
--- a/tests/dna_rhizome
+++ b/tests/dna_rhizome
@@ -65,10 +65,7 @@ unpack_manifest_for_grep() {
    local filename="$1"
    re_service='[A-Za-z0-9_]\+'
    re_size=$(( $(cat "$filename" | wc -c) + 0 ))
-   re_filehash=$($servald rhizome hash file "$filename")
-   if [ -z "$re_filehash" ]; then
-      error "Could not compute rhizome hash of $filename"
-   fi
+   compute_filehash re_filehash "$filename"
    re_manifestid='[0-9a-fA-F]\{64\}'
    re_name="${filename##*/}" # TODO should escape grep metacharacters
    # If there is a manifest file that looks like it matches this payload
@@ -139,6 +136,15 @@ extract_manifest_filehash() {
 
 extract_manifest_version() {
    extract_manifest "$1" "$2" version '[0-9]\{1,\}'
+}
+
+compute_filehash() {
+   local _var="$1"
+   local _file="$2"
+   local _hash=$($servald rhizome hash file "$_file") || error "$servald failed to compute file hash"
+   [ -z "${_hash//[0-9a-fA-F]/}" ] || error "file hash contains non-hex: $_hash"
+   [ "${#_hash}" -eq 128 ] || error "file hash incorrect length: $_hash"
+   [ -n "$_var" ] && eval $_var=$_hash
 }
 
 doc_InitialEmptyList="Initial list is empty"
@@ -474,24 +480,40 @@ test_AddMeshMSCreate() {
    assert diff file1 file1x
 }
 
-doc_AddMeshMSGrow="Second add MeshMS updates manifest"
+doc_AddMeshMSGrow="Subsequent add MeshMS updates manifest and removes old payload"
 setup_AddMeshMSGrow() {
    setup_servald_rhizome
    echo "Message1" >file1
-   echo "Message2" >file2
    echo -e "service=MeshMS1\nsender=$sid\nrecipient=$sid1" >file1.manifest
-   executeOk $servald rhizome add file $sid '' file1 file1.manifest
-   extract_manifest_id id file1.manifest
-   extract_manifest_BK bk file1.manifest
-   echo -e "id=$id\nBK=$bk\nservice=MeshMS1\nsender=$sid\nrecipient=$sid1" >file2.manifest
 }
 test_AddMeshMSGrow() {
-   executeOk $servald rhizome add file $sid '' file2 file2.manifest
-   extract_manifest_filehash filehash file2.manifest
+   executeOk $servald rhizome add file $sid '' file1 file1.manifest
    executeOk $servald rhizome list
-   assert_rhizome_list file2
-   executeOk $servald rhizome extract file $filehash file2x
-   assert diff file2 file2x
+   assert_rhizome_list file1
+   extract_manifest_id id file1.manifest
+   extract_manifest_filehash filehash file1.manifest
+   extract_manifest_BK bk file1.manifest
+   local -a ofilehashes=()
+   for m in 2 3 4 5; do
+      ofilehashes+=("$filehash")
+      echo -e "id=$id\nBK=$bk\nservice=MeshMS1\nsender=$sid\nrecipient=$sid1" >file1.manifest
+      echo "Message$m" >>file1
+      executeOk $servald rhizome add file $sid '' file1 file1.manifest
+      executeOk $servald rhizome list
+      assert_rhizome_list file1
+      extract_manifest_id idx file1.manifest
+      extract_manifest_filehash filehashx file1.manifest
+      extract_manifest_BK bkx file1.manifest
+      compute_filehash filehash file1
+      assert --message="manifest ID remains the same" [ "$idx" = "$id" ]
+      assert --message="manifest BK remains the same" [ "$bkx" = "$bk" ]
+      assert --message="filehash is for new file" [ "$filehash" = "$filehashx" ]
+      executeOk $servald rhizome extract file "$filehash" file1x
+      assert --message="extracted payload is correct" diff file1 file1x
+      for ofilehash in "${ofilehashes[@]}"; do
+         execute --exit-status=1 --stderr $servald rhizome extract file "$ofilehash"
+      done
+   done
 }
 
 doc_AddMeshMSMissingSender="Add MeshMS without sender fails"
